dataset_path: "datasets/strategyqa.parquet"
model_name: "openai/gpt-oss-20b"
dataset_prefix: "Please answer the following question by selecting one of the answer choices Yes or No. Provide your answer as Yes or No.\n"
batch_size: 16