dataset_path: "datasets/lsat-all.parquet"
model_name: "Qwen/Qwen3-8B"
dataset_prefix: "Please answer the following question by selecting one of the answer choices (A, B, C, D, or E). Provide your answer as only the letter corresponding to your choice. Directly answer the question with no explanation.\n"
batch_size: 16